# Generated by Django 2.0.1 on 2018-02-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20180224_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_num',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
    ]
